import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptPath = fileURLToPath(import.meta.url);
const scriptDir = path.dirname(scriptPath);
const siteDir = path.resolve(scriptDir, '..');
const repoRoot = path.resolve(siteDir, '..');
const generatedDir = path.join(siteDir, '.generated');

const sourceRoots = ['docs', 'schema', 'dev', 'ai'];
const ignoredPathParts = new Set([
  'node_modules',
  'dist',
  '.cache',
  'coverage',
  '.generated',
  '.vitepress',
]);

function isAiTaskDirectoryRootMarkdown(sourceRel) {
  return /^ai\/tasks\/[^/]+\/README\.md$/.test(sourceRel);
}

function shouldProjectMarkdown(sourceRel) {
  if (!sourceRel.startsWith('ai/tasks/')) {
    return true;
  }

  if (sourceRel === 'ai/tasks/README.md' || sourceRel === 'ai/tasks/material-index.md') {
    return true;
  }

  return isAiTaskDirectoryRootMarkdown(sourceRel);
}

function toPosixPath(value) {
  return value.split(path.sep).join('/');
}

function targetPathForSource(sourceRel) {
  if (sourceRel.endsWith('/README.md')) {
    return sourceRel.replace(/\/README\.md$/, '/index.md');
  }
  if (sourceRel === 'README.md') {
    return 'index.md';
  }
  return sourceRel;
}

function routeForTarget(targetRel) {
  const withoutExt = targetRel.replace(/\.md$/, '');
  if (withoutExt.endsWith('/index')) {
    return `/${withoutExt.slice(0, -'/index'.length)}/`;
  }
  return `/${withoutExt}`;
}

async function listMarkdownFiles(rootRel) {
  const rootAbs = path.join(repoRoot, rootRel);
  const files = [];

  async function walk(currentAbs) {
    const entries = await readdir(currentAbs, { withFileTypes: true });
    for (const entry of entries) {
      if (ignoredPathParts.has(entry.name)) {
        continue;
      }

      const entryAbs = path.join(currentAbs, entry.name);
      if (entry.isDirectory()) {
        await walk(entryAbs);
        continue;
      }

      if (!entry.isFile() || !entry.name.endsWith('.md')) {
        continue;
      }

      const sourceRel = toPosixPath(path.relative(repoRoot, entryAbs));
      if (!shouldProjectMarkdown(sourceRel)) {
        continue;
      }

      files.push(sourceRel);
    }
  }

  await walk(rootAbs);
  return files;
}

function normalizeMarkdown(markdown, sourcePath) {
  const notice = [
    '> [!NOTE]',
    '> This page is generated from repository Markdown.',
    '> Edit the source file instead of this projected copy.',
    `> Source: \`${sourcePath.replaceAll('\\', '/')}\``,
    '',
  ].join('\n');

  return `${notice}${markdown}`;
}

async function copyMarkdown(sourceRel, targetRel) {
  const sourcePath = path.join(repoRoot, sourceRel);
  const targetPath = path.join(generatedDir, targetRel);
  const markdown = await readFile(sourcePath, 'utf8');
  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, normalizeMarkdown(markdown, sourceRel), 'utf8');
}

async function writeIndex() {
  const index = `# LogicIR Docs

This site is a static browsing projection for existing repository Markdown. It
is a helper for local development and review, not a documentation source of
truth.

## Start Here

- [Reader docs](./docs/)
- [Schema docs](./schema/)
- [Development docs](./dev/)
- [AI task material index](./ai/tasks/material-index)
- [All projected documents](./all-documents)

## Source Boundaries

- Reader-facing source: \`docs/\`
- Published schema route: \`schema/\`
- Human development source: \`dev/\`
- AI/autonomous evidence source: \`ai/\`

Edit those source files directly. This VitePress content is generated by
\`yarn docs:sync\`.
`;

  await writeFile(path.join(generatedDir, 'index.md'), index, 'utf8');
}

async function writeAllDocumentsIndex(copiedFiles) {
  const sections = new Map();
  for (const [sourceRel, targetRel] of copiedFiles) {
    const [section] = sourceRel.split('/');
    if (!sections.has(section)) {
      sections.set(section, []);
    }
    sections.get(section).push([sourceRel, targetRel]);
  }

  const lines = [
    '# All Projected Documents',
    '',
    'This index is generated from projected Markdown under `docs/`, `dev/`, and the selected public AI entry pages.',
    '',
  ];

  for (const [section, entries] of [...sections.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`## ${section}`, '');
    for (const [sourceRel, targetRel] of entries.sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`- [${sourceRel}](${routeForTarget(targetRel)})`);
    }
    lines.push('');
  }

  await writeFile(path.join(generatedDir, 'all-documents.md'), lines.join('\n'), 'utf8');
}

export async function syncContent() {
  await rm(generatedDir, { recursive: true, force: true });
  await mkdir(generatedDir, { recursive: true });

  const sourceFiles = (await Promise.all(sourceRoots.map((root) => listMarkdownFiles(root))))
    .flat()
    .sort();
  const copiedFiles = sourceFiles.map((sourceRel) => [sourceRel, targetPathForSource(sourceRel)]);

  await Promise.all(copiedFiles.map(([source, target]) => copyMarkdown(source, target)));
  await writeIndex();
  await writeAllDocumentsIndex(copiedFiles);

  console.log(`Synced ${copiedFiles.length} Markdown files to ${path.relative(repoRoot, generatedDir)}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === scriptPath) {
  await syncContent();
}
